# head
menu:
  Home: /
  Writing: /archives
  Project: 'https://github.com/tabliu/'
  About: /about
  # sitemap: /sitemap.xml
  # other menus

rss: /atom.xml
favicon: /favicon.ico

date_format: 'MMMM D, YYYY'

google_verification: false  # your token
google_analytics: false   # your id

# livere_id: 'city'
# livere_uid: 'MTAyMC8zNTQ2MS8xMTk5Nw=='

start_year: 2015

reward_images: # add your qr image
# - type: '微信'
#   url: '/img/wechat.png'
# - type: '支付宝'
#   url: '/img/wechat.png'

